const input=document.querySelector('#fileInput'),zone=document.querySelector('#dropzone'),list=document.querySelector('#fileList'),section=document.querySelector('#filesSection'),count=document.querySelector('#fileCount'),status=document.querySelector('#status'),toast=document.querySelector('#toast');
let items=[],toastTimer,ffmpegPromise;
const imageTargets=[['image/png','PNG'],['image/jpeg','JPG'],['image/webp','WEBP'],['image/avif','AVIF']];
const audioTargets=[['mp3','MP3'],['wav','WAV'],['ogg','OGG'],['aac','AAC'],['m4a','M4A'],['flac','FLAC']];
const videoTargets=[['mp4','MP4'],['webm','WEBM'],['mov','MOV'],['mkv','MKV'],['gif','GIF']];
const textTargets=[['text/plain','TXT'],['text/html','HTML'],['text/csv','CSV'],['application/json','JSON']];
function extension(name){return(name.split('.').pop()||'').toLowerCase()}
function optionsFor(file){const ext=extension(file.name),type=file.type.toLowerCase();if(type.startsWith('image/')||['png','jpg','jpeg','webp','bmp','gif','avif','tif','tiff'].includes(ext))return imageTargets.filter(([,label])=>label!=='AVIF');if(type.startsWith('audio/')||['mp3','wav','ogg','aac','m4a','flac','opus','wma','aiff'].includes(ext))return audioTargets;if(type.startsWith('video/')||['mp4','webm','mov','mkv','avi','m4v','3gp','mpeg','mpg'].includes(ext))return videoTargets;if(type==='text/csv'||ext==='csv')return textTargets;if(type==='application/json'||ext==='json')return textTargets;if(type.startsWith('text/')||['txt','md','html','xml','log','tsv'].includes(ext))return textTargets;return[]}
function addFiles(files){let added=0;for(const file of files){if(items.some(x=>x.file.name===file.name&&x.file.size===file.size&&x.file.lastModified===file.lastModified))continue;const formats=optionsFor(file);const ext=extension(file.name),kind=file.type.startsWith('image/')||['png','jpg','jpeg','webp','bmp','gif','avif','tif','tiff'].includes(ext)?'image':file.type.startsWith('audio/')||audioTargets.some(([f])=>f===ext)||['opus','wma','aiff'].includes(ext)?'audio':file.type.startsWith('video/')||videoTargets.some(([f])=>f===ext)||['avi','m4v','3gp','mpeg','mpg'].includes(ext)?'video':'text';items.push({file,formats,format:formats[0]?.[0]||'',error:formats.length?'':'Формат не поддерживается',kind});added++}render();if(added)showToast(added===1?'Файл добавлен':`Добавлено файлов: ${added}`)}
function render(){section.hidden=!items.length;count.textContent=items.length?String(items.length):'';list.replaceChildren();items.forEach((item,index)=>{const row=document.createElement('div');row.className='file-row';const info=document.createElement('div');info.className='file-info';const badge=document.createElement('span');badge.className='file-badge';badge.textContent=extension(item.file.name).slice(0,5).toUpperCase()||'FILE';const labels=document.createElement('div');labels.style.minWidth='0';const name=document.createElement('div');name.className='file-name';name.textContent=item.file.name;const size=document.createElement('div');size.className='file-size';size.textContent=item.error||formatSize(item.file.size);labels.append(name,size);info.append(badge,labels);row.append(info);const select=document.createElement('select');select.className='format-select';select.setAttribute('aria-label',`Формат для ${item.file.name}`);if(!item.formats.length){const op=document.createElement('option');op.textContent='Не поддерживается';select.append(op);select.disabled=true}else item.formats.forEach(([type,label])=>{const op=document.createElement('option');op.value=type;op.textContent=label;select.append(op)});select.value=item.format;select.addEventListener('change',()=>item.format=select.value);row.append(select);const remove=document.createElement('button');remove.className='remove-file';remove.type='button';remove.title='Удалить файл';remove.setAttribute('aria-label',`Удалить ${item.file.name}`);remove.textContent='×';remove.addEventListener('click',()=>{items.splice(index,1);render()});row.append(remove);list.append(row)});status.textContent=items.some(x=>x.error)?'Есть неподдерживаемые файлы':'Готово к конвертации'}
function formatSize(n){if(n<1024)return`${n} Б`;if(n<1048576)return`${(n/1024).toFixed(1)} КБ`;return`${(n/1048576).toFixed(1)} МБ`}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3300)}
document.querySelector('#browse').addEventListener('click',()=>input.click());zone.addEventListener('click',e=>{if(e.target.closest('button'))return;input.click()});zone.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}});input.addEventListener('change',()=>{addFiles(input.files);input.value=''});
for(const event of['dragenter','dragover'])document.addEventListener(event,e=>{e.preventDefault();zone.classList.add('dragover')});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)zone.classList.remove('dragover')});document.addEventListener('drop',e=>{e.preventDefault();zone.classList.remove('dragover');if(e.dataTransfer?.files?.length){ripple(e.clientX,e.clientY);addFiles(e.dataTransfer.files)}});
function ripple(x,y){const el=document.createElement('span');el.className='wave';el.style.setProperty('--x',`${x}px`);el.style.setProperty('--y',`${y}px`);document.body.append(el);el.addEventListener('animationend',()=>el.remove(),{once:true})}
document.querySelector('#clearAll').addEventListener('click',()=>{items=[];render()});
document.querySelector('#convertAll').addEventListener('click',async e=>{const btn=e.currentTarget,valid=items.filter(x=>!x.error);if(!valid.length){showToast('Добавьте поддерживаемые файлы');return}btn.disabled=true;let done=0;const errors=[];for(const item of valid){try{status.textContent=`Обработка ${done+1} из ${valid.length}…`;const blob=item.kind==='image'?await convertImage(item.file,item.format):item.kind==='text'?await convertText(item.file,item.format):await convertMedia(item.file,item.format);download(blob,withExtension(item.file.name,item.format));done++}catch(err){console.error(err);errors.push(`${item.file.name}: ${err.message}`)}}btn.disabled=false;status.textContent=errors.length?errors.join(' · '):'Готово к конвертации';if(errors.length)showToast(errors[0]);else showToast(`Готово: ${done} файл(ов) скачано`)});
function withExtension(name,type){const ext=type.includes('/')?({'image/jpeg':'jpg','image/png':'png','image/webp':'webp','text/plain':'txt','text/html':'html','text/csv':'csv','application/json':'json'}[type]||'bin'):type;return`${name.replace(/\.[^.]+$/,'')}.${ext}`}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000)}
async function convertImage(file,type){const bitmap=await createImageBitmap(file);try{const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);return await new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Браузер не смог декодировать это изображение')),type,type==='image/jpeg'?.92:undefined))}finally{bitmap.close()}}
async function convertText(file,type){const text=await file.text();if(type==='application/json'){let data;try{data=JSON.parse(text)}catch{data=parseCsv(text)}return new Blob([JSON.stringify(data,null,2)],{type})}if(type==='text/csv'){const rows=file.name.toLowerCase().endsWith('.json')?(()=>{const d=JSON.parse(text);return Array.isArray(d)?d:[d]})():parseCsv(text);return new Blob([toCsv(rows)],{type:'text/csv;charset=utf-8'})}if(type==='text/html')return new Blob([`<!doctype html><meta charset="utf-8"><pre>${text.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</pre>`],{type:'text/html;charset=utf-8'});return new Blob([text],{type:'text/plain;charset=utf-8'})}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=false;else cell+=c}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(v=>v!==''))rows.push(row);row=[]}else cell+=c}row.push(cell);if(row.some(v=>v!==''))rows.push(row);if(rows.length<2)return rows.flat();const headers=rows.shift();return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))}
function toCsv(data){if(!Array.isArray(data))data=[data];if(!data.length)return'';const objects=data.every(x=>x&&typeof x==='object'&&!Array.isArray(x));let rows;if(objects){const headers=[...new Set(data.flatMap(Object.keys))];rows=[headers,...data.map(x=>headers.map(h=>x[h]??''))]}else rows=data.map(x=>Array.isArray(x)?x:[x]);return rows.map(r=>r.map(v=>{const s=String(v??'');return/[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}).join(',')).join('\r\n')}
async function loadFFmpeg(){if(!ffmpegPromise)ffmpegPromise=(async()=>{const base=new URL('./vendor/ffmpeg/',document.baseURI),{FFmpeg}=await import(new URL('index.js',base).href),ffmpeg=new FFmpeg();ffmpeg.on('progress',({progress})=>{if(Number.isFinite(progress))status.textContent=`Конвертация медиа ${Math.round(progress*100)}%`});await ffmpeg.load({classWorkerURL:new URL('classes.js',base).href,coreURL:new URL('ffmpeg-core.js',base).href,wasmURL:new URL('ffmpeg-core.wasm',base).href});return ffmpeg})();return ffmpegPromise}
async function toBlobURL(url,type){const r=await fetch(url);if(!r.ok)throw new Error('Не удалось загрузить модуль конвертации');return URL.createObjectURL(new Blob([await r.arrayBuffer()],{type}))}
async function convertMedia(file,format){if(location.protocol==='file:')throw new Error('Откройте сайт через localhost или GitHub Pages');const ffmpeg=await loadFFmpeg(),id=crypto.randomUUID(),inputName=`input-${id}.${extension(file.name)||'bin'}`,outputName=`output-${id}.${format}`;try{await ffmpeg.writeFile(inputName,new Uint8Array(await file.arrayBuffer()));const args=['-y','-i',inputName];if(['mp3','aac','ogg','flac'].includes(format))args.push('-vn');if(format==='mp3')args.push('-c:a','libmp3lame','-q:a','2');if(format==='aac')args.push('-c:a','aac','-b:a','192k');if(format==='ogg')args.push('-c:a','libvorbis','-q:a','5');if(format==='flac')args.push('-c:a','flac');if(format==='wav')args.push('-c:a','pcm_s16le');if(format==='mp4')args.push('-c:v','libx264','-preset','ultrafast','-c:a','aac','-movflags','+faststart');if(format==='webm')args.push('-c:v','libvpx','-c:a','libvorbis');if(format==='gif')args.push('-vf','fps=12,scale=720:-1:flags=lanczos');args.push(outputName);const result=await ffmpeg.exec(args,120000);if(result!==0)throw new Error('FFmpeg не смог декодировать источник или записать этот формат');const data=await ffmpeg.readFile(outputName);const mime=format==='mp3'?'audio/mpeg':format==='wav'?'audio/wav':format==='mp4'?'video/mp4':format==='webm'?'video/webm':format==='ogg'?'audio/ogg':format==='gif'?'image/gif':format==='flac'?'audio/flac':format==='aac'?'audio/aac':'application/octet-stream';return new Blob([data],{type:mime})}finally{try{await ffmpeg.deleteFile(inputName)}catch{}try{await ffmpeg.deleteFile(outputName)}catch{}}}
